---
name: Publish Python ðŸ distributions ðŸ“¦ to PyPI
on:
  push:
    tags:
      - "*"
jobs:

  extract-tag:  
    runs-on: ubuntu-latest  
    outputs:  
      version: ${{ steps.extract_tag.outputs.tag }}  
    steps:  
      - uses: actions/checkout@v4
      - id: extract_tag  
        name: Extract tag name  
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"  

  build-and-publish-test-pypi:
    needs: extract-tag
    runs-on: ubuntu-latest
    environment: 
      name: pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: python3 -m pip install setuptools wheel twine semver packaging
      - name: Get correct version for TestPyPI release  
        id: check_version  
        run: |  
          VERSION=${{ needs.extract-tag.outputs.version }}  
          PACKAGE_NAME="dspy-ai-test-hmoazam"
          echo "Checking if $VERSION for $PACKAGE_NAME exists on TestPyPI"  
          NEW_VERSION=$(python3 .github/workflows/build_utils/test_version.py $PACKAGE_NAME $VERSION)  
          echo "Version to be used for TestPyPI release: $NEW_VERSION"  
          echo "::set-output name=version::$NEW_VERSION"  
      - name: Update version in setup.py
        run: sed -i '/#replace_package_version_marker/{n;s/version="[^"]*"/version="${{ steps.check_version.outputs.version }}"/;}' setup.py
      - name: Update version in pyproject.toml
        run: sed -i '/#replace_package_version_marker/{n;s/version="[^"]*"/version="${{ steps.check_version.outputs.version }}"/;}' pyproject.toml        
      - name: Update package name in setup.py
        run: sed -i '/#replace_package_name_marker/{n;s/name="[^"]*"/name="dspy-ai-test-hmoazam"/;}' setup.py 
      - name: Update package name in pyproject.toml
        run: sed -i '/#replace_package_name_marker/{n;s/name="[^"]*"/name="dspy-ai-test-hmoazam"/;}' pyproject.toml  
      - name: Build a binary wheel
        run: python3 setup.py sdist bdist_wheel
      - name: Publish distribution ðŸ“¦ to test-PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # This requires a trusted publisher to be setup in pypi/testpypi
        with: 
          repository-url: https://test.pypi.org/legacy/
      - uses: stefanzweifel/git-auto-commit-action@v5 # auto commit changes to main

  build-and-publish-pypi:
    needs: [extract-tag, build-and-publish-test-pypi]
    runs-on: ubuntu-latest
    environment: 
      name: pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: python3 -m pip install setuptools wheel twine
      - name: Update version in setup.py (dspy)
        run: sed -i '/#replace_package_version_marker/{n;s/version="[^"]*"/version="${{ needs.extract-tag.outputs.version }}"/;}' setup.py
      - name: Update version in pyproject.toml
        run: sed -i '/#replace_package_version_marker/{n;s/version="[^"]*"/version="${{ needs.extract-tag.outputs.version }}"/;}' pyproject.toml
      # Publish to dspy
      - name: Update package name in setup.py  
        run: |
          sed -i '/#replace_package_name_marker/{n;s/name="[^"]*"/name="test-pkg-hmoazam"/;}' setup.py
      - name: Update package name in pyproject.toml
        run: sed -i '/#replace_package_name_marker/{n;s/name="[^"]*"/name="test-pkg-hmoazam"/;}' pyproject.toml
      - name: Build a binary wheel
        run: python3 setup.py sdist bdist_wheel
      - name: Publish distribution ðŸ“¦ to PyPI (dspy)
        uses: pypa/gh-action-pypi-publish@release/v1 # This requires a trusted publisher to be setup in pypi
        with: 
          attestations: false
        # Publish to dspy-ai
      - name: Update version in setup.py (dspy-ai)
        run: sed -i '/#replace_package_version_marker/{n;s/version="[^"]*"/version="${{ needs.extract-tag.outputs.version }}"/;}' ./dspy/.internal_dspyai/setup.py
      - name: Update package name in setup.py  
        run: sed -i '/#replace_package_name_marker/{n;s/name="[^"]*"/name="dspy-ai-hmoazam"/;}' ./dspy/.internal_dspyai/setup.py
      - name: Update dspy dependency version in setup.py  
        run: |
          sed -i '/#replace_dspy_version_marker/{n;s/dspy==[^"]*/dspy>=${{ needs.extract-tag.outputs.version }}/;}' ./dspy/.internal_dspyai/setup.py  
      - name: Build a binary wheel
        run: python3 ./dspy/.internal_dspyai/setup.py sdist bdist_wheel
      - name: Publish distribution ðŸ“¦ to PyPI (dspy-ai)
        uses: pypa/gh-action-pypi-publish@release/v1 # This requires a trusted publisher to be setup in pypi
        with: 
          attestations: false
      - uses: stefanzweifel/git-auto-commit-action@v5 # auto commit changes to main